name: airguard_new
description: "AirGuard - Air Quality Monitoring System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^1.2.0
  intl: ^0.20.3
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.31.1

flutter:
  uses-material-design: true
