// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV0-cEzSH1A8kV-rtW0JwI2Oy5fbM5bJ4',
    appId: '1:493532620829:web:8c37e48094576f11507ef4',
    messagingSenderId: '493532620829',
    projectId: 'airguard-b514a',
    authDomain: 'airguard-b514a.firebaseapp.com',
    storageBucket: 'airguard-b514a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpwvs_Dgx9MPc4EV8OwUKu-vVVhm-CeB4',
    appId: '1:493532620829:android:bf71e583d35ddf2d507ef4',
    messagingSenderId: '493532620829',
    projectId: 'airguard-b514a',
    storageBucket: 'airguard-b514a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTGWtSukns14bGnqX5N88yLVlFj8HcvSk',
    appId: '1:493532620829:ios:04ab0ac6386d95f5507ef4',
    messagingSenderId: '493532620829',
    projectId: 'airguard-b514a',
    storageBucket: 'airguard-b514a.firebasestorage.app',
    iosBundleId: 'com.example.airguardNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTGWtSukns14bGnqX5N88yLVlFj8HcvSk',
    appId: '1:493532620829:ios:04ab0ac6386d95f5507ef4',
    messagingSenderId: '493532620829',
    projectId: 'airguard-b514a',
    storageBucket: 'airguard-b514a.firebasestorage.app',
    iosBundleId: 'com.example.airguardNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV0-cEzSH1A8kV-rtW0JwI2Oy5fbM5bJ4',
    appId: '1:493532620829:web:392556bdc84ad0a7507ef4',
    messagingSenderId: '493532620829',
    projectId: 'airguard-b514a',
    authDomain: 'airguard-b514a.firebaseapp.com',
    storageBucket: 'airguard-b514a.firebasestorage.app',
  );
}
